-- Generated by node scripts/generate-korean-seed.mjs. Run after 20261007_multilingual.sql.

-- Inserts missing starter content only; never resets edits or learning progress.

begin;

insert into public.vocabulary_groups(id, title, language_code, sort_order) values
  ('ko-daily', 'Giao tiếp hằng ngày', 'ko', 0),
  ('ko-work', 'Công việc', 'ko', 1)
on conflict(id) do nothing;

insert into public.vocabulary_words(id, word, group_id, meaning, example, ipa, reading, romanization, cloze_text, cloze_answer, sort_order) values
  ('ko-hello', '안녕하세요', 'ko-daily', 'xin chào', '안녕하세요. 저는 민수입니다.', '', '', 'annyeonghaseyo', '_____. 저는 민수입니다.', '안녕하세요', 0),
  ('ko-thanks', '감사합니다', 'ko-daily', 'cảm ơn', '도와주셔서 감사합니다.', '', '', 'gamsahamnida', '도와주셔서 _____.', '감사합니다', 1),
  ('ko-school', '학교', 'ko-daily', 'trường học', '저는 학교에 갑니다.', '', '[학꾜]', 'hakgyo', '저는 _____에 갑니다.', '학교', 2),
  ('ko-friend', '친구', 'ko-daily', 'bạn bè', '친구를 만나요.', '', '', 'chingu', '_____를 만나요.', '친구', 3),
  ('ko-time', '시간', 'ko-daily', 'thời gian', '지금 시간이 있어요.', '', '', 'sigan', '지금 _____이 있어요.', '시간', 4),
  ('ko-company', '회사', 'ko-work', 'công ty', '회사에서 일해요.', '', '', 'hoesa', '_____에서 일해요.', '회사', 0),
  ('ko-meeting', '회의', 'ko-work', 'cuộc họp', '오늘 회의가 있어요.', '', '', 'hoeui', '오늘 _____가 있어요.', '회의', 1),
  ('ko-document', '문서', 'ko-work', 'tài liệu', '문서를 보내 주세요.', '', '', 'munseo', '_____를 보내 주세요.', '문서', 2),
  ('ko-schedule', '일정', 'ko-work', 'lịch trình', '일정을 확인해요.', '', '', 'iljeong', '_____을 확인해요.', '일정', 3),
  ('ko-deadline', '마감', 'ko-work', 'hạn chót', '마감은 내일이에요.', '', '', 'magam', '_____은 내일이에요.', '마감', 4)
on conflict do nothing;

commit;
